### ISSUE TITLE
L'utente chickenlory segnala che non si possono modificare gli articoli

### ISSUE THREAD

**Issue by chickenmatty** [ToastEnergy/ToastBlog#1]
non godo

**Comment by ssebastianoo** [comment]
questo perchè qualcuno non gli ha dato l'accesso a supabase

**Comment by ssebastianoo** [comment]
![FNVM7hJXwAURAYg](https://user-images.githubusercontent.com/48064277/181298978-17b5a232-d544-4795-9dd3-4c8f97818131.jpg)

**Comment by ssebastianoo** [comment]
ne ridiamo
